### ISSUE TITLE
思客课程总结

### ISSUE THREAD

**Issue by cyio** [cyio/cyio.github.io#1]
课程地址：[思客教学 - 从 0 到 1 实现响应式个人网站](http://sike.io/courses/css0to1/)
我的作业：[Profile](http://cyio.github.io/sike-css0to1-profile/)
课程评价：任务看似简单，但安排得很好，有重点知识穿插，有留下的坑等学员踩。逼着你用Github、Markdown、每天打卡，有导师指导，可以看小伙伴们的作业、心得，还有微信声叮叮的直接沟通。就学习方式而言，比自己闷头学，好处大大的多。
# 重要知识点
### 如何清除浮动（float）？

两个解决办法：
方法一：设置溢出为隐藏

``` css
overflow:hidden
```

强制容器有足够的**高度**包围浮动元素（默认visible的话，浮动元素会溢出）
这时容器被称为  **block formatting context (BFC)**

方法二： 添加空元素

``` css
clearfix:after { 
    content:"";
    display:table; 
    clear:both;
}
```
### 为什么要用 border-box ？

不计算 padding 和 border 的宽度，轻松用百分比布局

``` css
.photos__list li {
    float: left;
    padding: 10px;
    width: 25%;
    box-sizing: border-box;
}
```
### margin（垂直外边距）折叠或塌陷

情形之一是发生在父元素和第一个或最后一个子元素之间，解决办法是，给父元素设 padding或border（相邻元素只留大值）
### 两个布局方式的差异

（考虑布局是否对空格敏感）
![image](https://cloud.githubusercontent.com/assets/3146103/7880721/ddca866a-062e-11e5-8a63-8130f58f6616.png)
### 问题排除
- 标点用对没？比如，分号写成了冒号
- 试着给元素或邻近元素加上宽高
- 浏览器自带风格影响（如 ul 的左内边距）
### 布局模型
1. float  + 百分比（配合 border-box ）
2. absolute （典型场景：输入框标签的布局，label显示在input的右侧）
### 编写规范

具体的属性排序可以按照以下的规则：
1. 定位属性: position, float, z-index, clear
2. 盒模型相关属性: padding, margin, display, width, height, border
3. 字体相关 : font
4. CSS2 视觉相关属性 : background
5. CSS3 属性 : border-radius, box-shadow
### 其它
-  inline 元素无法设置垂直边距（padding , margin）
- background-attachment: fixed; 随视角滚动还是固定
### 代码片段

为图片预留空间

``` css
.whatido ul li {
    padding-top: 100px;
}
```

伪元素下划线

``` css
.info-section header h2:after {
    display: block;
    content: "";
    background-color: #333;
    width: 2em;
    height: .1em;
    margin: .4em auto;
}
```
