### ISSUE TITLE
border可以细到1px以下吗？

### ISSUE THREAD

**Issue by cyio** [cyio/cyio.github.io#15]
补充：[Retina屏的移动设备如何实现真正1px的线？ | Alon's Blog](http://jinlong.github.io/2015/05/24/css-retina-hairlines/)

问题出自这篇文章[css3使用技巧：细线边框的3种不同的写法_大前端](http://www.daqianduan.com/5935.html?utm_source=tuicool) 

作者给出了三种变通方案，能实现但改起来会比较麻烦。
我测试px最小是1，但pt可以用小数。所以，通过换单位，border应该是可以更细一点。

``` css
li{
  list-style-type: none;
  border-bottom: 0.75pt solid #eee;
}
```
