### ISSUE TITLE
fiznote首页排版问题

### ISSUE THREAD

**Issue by cyio** [cyio/cyio.github.io#3]
已在[V2EX](https://www.v2ex.com/t/199226)上提给开发者

**修改之前**

![image](https://cloud.githubusercontent.com/assets/3146103/8204454/54988e4a-151b-11e5-9f03-4fdddb2ee2f5.png)

**修改后**
![image](https://cloud.githubusercontent.com/assets/3146103/8204057/7c4bce64-1518-11e5-8f1b-ea515df8ca3c.png)
### 排版问题：
- 字体偏大，PC端用户会不舒服
- 文字太挤，行高没设置好
- 标题、描述之间，没有设置合适的间距
- 缩进错误
### 解决如下：

**HTML代码修改如下**（为描述部分添加p标签，便于用CSS做缩进）

``` html
<span class="sec-text">
    <p>FizNote可以让您从自己关心的角度随时去了解您的业务。通过合理的标签设置，您可以快速知道诸如“张三今年差旅费多少？”“哪个商品上个月卖的好？”之类的问题。</p>
    <div class="la"><b class="text-success">自由查询，不用特地去问相关人员</b></div>
</span>
```

**CSS修改部分** 

``` css
/* 板块描述调小字号，增加行高。把描述文字的颜色加深（建议） */
.sec-text {
    font-size: 16px;
    line-height: 1.5em;
    color: #666;
}

/* 为板块描述设置缩进 */
.sec-text>p {
    text-indent: 2em;
}

/* 版块标题字号调小，并增加与板块描述的间距 */
.sec-title {
    font-size: 25px;
    margin-bottom: 20px;
}

/* 导航部分字号调小 */
#nav {
    font-size: 14px;
}    
```
