### ISSUE TITLE
上手SCSS

### ISSUE THREAD

**Issue by cyio** [cyio/cyio.github.io#37]
记录几个不熟悉的用法：

引用父选择符，注意最后一行：

``` css
a {
  font-weight: bold;
  text-decoration: none;
  &:hover { text-decoration: underline; }
  body.firefox & { font-weight: normal; }
}
```

嵌套属性，如字体：

``` css
.funky {
  font: {
    family: fantasy;
    size: 30em;
    weight: bold;
  }
}
```

变量运算时用 #{} 包裹

``` css
p {
  $font-size: 12px;
  $line-height: 30px;
  font: #{$font-size}/#{$line-height};
}
```

颜色也可以运算

``` css
p {
  color: #010203 + #040506;
}
```

有alpha值的要保持一致

``` css
p {
  color: rgba(255, 0, 0, 0.75) + rgba(0, 255, 0, 0.75);
}
```

用`!`设置默认值，变量没有赋值时用

``` css
$content: "First content";
$content: "Second content?" !default;
$new_content: "First time reference" !default;

#main {
  content: $content;
  new-content: $new_content;
}
```

选择器插值

``` css
$prefix: ui
.#{$prefix}-button
  color: #333;
```

灵活的mixin，类似函数加参数

``` css
@mixin col  ($width) {
  width: $width;
  float: left;
```

设置默认参数

``` css
@mixin col  ($width : 50%) {
  width: $width;
  float: left;
}
```

@extend 继承，将选择器插入目标，共享目标属性

``` css
.error {
  color:#f00;
}
.serious-error {
  @extend .error;
  border: 1px #f00;
}
```

媒体查询

``` css
@mixin col-sm ($width: 50%) {
  @media (min-width):768px) {
    width: $width;
    float: left;
  }
}
```

最佳实践，避免嵌套，保持结构，偍编译到最顶层

``` css
.main-sec {
  font-family: $main-sec-ff;

  @at-root {
    .main-sec-headline {
      font: {
        faamily: $main-sec-ff;
        size: 16px;
      }
    }

    .main-sec-detail {
      font-size: 12px;
    }
  }
}
```
