### ISSUE TITLE
CSS中的3D

### ISSUE THREAD

**Issue by cyio** [cyio/cyio.github.io#38]
首先定义透视对象 
`perspective($px)`决定了3D效果的强度
写成一行

``` css
#red .box {
  transform: perspective( 600px ) rotateY( 45deg );
  background-color: red;
}
```

或者单独定义透视

``` css
#blue {
  perspective: 600px;
}

#blue .box {
  transform: rotateY( 45deg );
  background-color: blue;
}
```

3D空间的**消失点**（也叫焦点）默认在中心位置，可以这样改

```
perspective-origin: 25% 75%;
```
