### ISSUE TITLE
electronic在高分辨率下的字体问题

### ISSUE THREAD

**Issue by cyio** [cyio/cyio.github.io#72]
在使用 electronic-wechat 遇到字小的问题，目前是这样解决的
在 inject 的 css 中加入如下代码：

``` css
body {
     zoom: 1.3;
}   
```

[High DPI support on Linux · Issue #615 · electron/electron](https://github.com/electron/electron/issues/615)
